schema_version: 1

context:
  version: "1.5.1"

package:
  name: ad
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/ad/ad-${{ version }}.tar.gz
  sha256: ee7c5dfe8744ba43bfac9e32b0c6e9f710ad71dc4174189c82f8a8a079bfb47b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.29.0
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - numpy

tests:
  - python:
      imports:
        - ad
        - ad.admath
        - ad.linalg
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://eggzec.github.io/ad/
  repository: https://github.com/eggzec/ad
  documentation: https://eggzec.github.io/ad/
  summary: Fast, transparent first- and second-order automatic differentiation
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - killua156
    - mgorny
